### ISSUE TITLE
How to put server in on-demand mode?

### ISSUE THREAD

**Issue by FoxxMD** [kristopolous/DRR#157]
[It's mentioned in the docs](https://github.com/kristopolous/DRR/wiki/Join-the-Federation#modes) but there are no instructions on how to actually do it. I searched through `indy_server.py` as well for "mode" and "demand" but didn't find anything.

**Comment by kristopolous** [comment]
oh yeah I removed that ... I need to update the documentation. Sorry.  As it turns out it wasn't a very useful construct.

**Comment by kristopolous** [comment]
yeah ... ok I've removed it.

The things that it couldn't do is have 
- historical archives after a subscription
- be able to have a reminder of things you are currently listening to
- have arbitrary time queries 

Quite a few other things ... it just wasn't worth it.  Furthermore, there's a few other services out there that do this in a show specific way.  You can select a show, say "Thom Hartman" and then record the future episode, then come back and download it.  It's of limited use.  The "always recording" mode is a simpler and more useful model.

**Comment by FoxxMD** [comment]
> it just wasn't worth it.

Sad to hear that :( It's what initially caught my attention. I know storage costs are low if you are using cloud storage but if I wanted to run a home server just to capture a few shows every week the disk cost would be enormous. 

> there's a few other services out there that do this in a show specific way.

Do you know them by name? I'd like to check them out.

I got a server up and running but I need take a look at your cloud code and implement something for amazon since that's my provider. I'm still interested in running a full server but I need to get s3 implemented since the cost is drastically lower ($0.005/GB/month).
